{{- if not .Values.telegram.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jmap2telegram.fullname" . }}
  labels:
    {{- include "jmap2telegram.labels" . | nindent 4 }}
type: Opaque
stringData:
  bot-token: {{ .Values.telegram.botToken | required "telegram.botToken (or telegram.existingSecret) is required" | quote }}
{{- end }}
